[tool]
[tool.poetry]
authors = ["Sprint Addons Team"]
description = ""
name = "Sprint v1"
version = "1.0"
[tool.poetry.dependencies]
pyttsx3 = { git = "https://github.com/nateshmbhat/pyttsx3" }
requests = { git = "https://github.com/requests/requests.git" }
